aa:
    chmod 777 ../../projects/maix_asr/build/maix_asr
	../../projects/maix_asr/build/maix_asr asr_wav2.cfg

bb:
    chmod 777 ../../projects/maix_asr/build/maix_asr
	../../projects/maix_asr/build/maix_asr asr_wav.cfg